name: Lint

on:
  push:
    branches: [ "main", "v1" ]
  pull_request:
    branches: [ "main", "v1" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustc-dev, llvm-tools-preview
      - name: Install Dylint
        run: cargo install cargo-dylint dylint-link
      - name: Run tests
        run: cargo test --workspace
